---
- name: Test AWS RHEL connectivity
  hosts: all
  gather_facts: true

  tasks:
    - name: Ping RHEL VM
      ansible.builtin.ping:

    - name: Show RHEL information
      ansible.builtin.debug:
        msg: >
          Connected to {{ inventory_hostname }}
          running {{ ansible_distribution }}
          {{ ansible_distribution_version }}