---
- name: Test ServiceNow API
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Display ServiceNow host
      ansible.builtin.debug:
        msg: "ServiceNow host is {{ lookup('env', 'SN_HOST') }}"

    - name: Test ServiceNow REST API
      ansible.builtin.uri:
        url: "{{ lookup('env', 'SN_HOST') }}/api/now/table/incident?sysparm_limit=1"
        method: GET
        user: "{{ lookup('env', 'SN_USERNAME') }}"
        password: "{{ lookup('env', 'SN_PASSWORD') }}"
        force_basic_auth: true
        validate_certs: true
        status_code: 200
        return_content: true
      register: servicenow_api

    - name: Display API response
      ansible.builtin.debug:
        msg: "{{ servicenow_api.json }}"