---
- name: Configure Windows
  hosts: windows
  gather_facts: true

  tasks:

    # ---------------------------------------------------------
    # Validate Windows host
    # ---------------------------------------------------------

    - name: Show hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Show operating system
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Show Ansible Windows user
      ansible.windows.win_whoami:
      register: windows_identity

    - name: Display Windows identity
      ansible.builtin.debug:
        var: windows_identity.account.account_name

    # ---------------------------------------------------------
    # Configure application
    # ---------------------------------------------------------

    - name: Install Apache
      chocolatey.chocolatey.win_chocolatey:
        name: apache-httpd
        state: present

    - name: Start Apache
      ansible.windows.win_service:
        name: Apache
        state: started
        start_mode: auto

    # ---------------------------------------------------------
    # Validate application
    # ---------------------------------------------------------

    - name: Get Apache service information
      ansible.windows.win_service:
        name: Apache
      register: apache_service

    # ---------------------------------------------------------
    # Retrieve EC2 metadata from Windows
    # ---------------------------------------------------------

    - name: Get EC2 metadata token
      ansible.windows.win_uri:
        url: http://169.254.169.254/latest/api/token
        method: PUT
        headers:
          X-aws-ec2-metadata-token-ttl-seconds: "21600"
        return_content: true
      register: ec2_metadata_token

    - name: Get EC2 public IPv4
      ansible.windows.win_uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        method: GET
        headers:
          X-aws-ec2-metadata-token: "{{ ec2_metadata_token.content }}"
        return_content: true
      register: ec2_public_ip

    # ---------------------------------------------------------
    # Demo output
    # ---------------------------------------------------------

    - name: Display server information
      ansible.builtin.debug:
        msg:
          - "OS: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "Hostname: {{ ansible_hostname }}"
          - "Private IP: {{ ansible_default_ipv4.address }}"
          - "Public IPv4: {{ ec2_public_ip.content }}"
          - "Apache: {{ apache_service.state }}"